---
title: "Proyecto Final"
author: Felipe Arguelles, Franza Estevez, Alejandro Iza, Lily Lopez, Mia Townsend,
  Edir Vidal
date: "18/12/2021"
output: html_document
---

```{r}
#install.packages("tidyverse")
#install.packages("ggplot2")
#install.packages("ggpubr")
#install.packages("dplyr")
#install.packages("GGally")
#install.packages("PTXQC")
#install.packages("nortest")
```

```{r setup,include=FALSE}
library(ggpubr)
library(dplyr)
library(nortest)
library(tidyverse) #tratamiento de datos
library(GGally) #análisis de relacion entre variables
library(ggplot2) #graficos
library(gridExtra)#validacion de condiciones para la regresion lineal
library(AICcmodavg) # Método Forward
```

```{r}
db<-read.csv("Bioestadistica.csv")
db = db[complete.cases(db),]
```

```{r}
#Limpieza de datos mediante eliminación de espacios vacíos
boxplot(db$Education_Expenditure)
```
# No se encontrar observaciones vacios y por lo tanto no se elimino ninguna. 

```{r}
dbf <- filter(db, Household_Head_Age>=18)
dbf <- dbf %>% select(Education_Expenditure,Main_Source_of_Income,Household_Head_Age,Household_Head_Sex,Total_members_employed) 
```

```{r}
#Variables resumidas para realizar un test de Normalidad
table(dbf$Total_members_employed)
table(dbf$Household_Head_Age)
summary(dbf$Education_Expenditure)
```
#Usamos el test de Lilliefors, el cual es un test basado en el test de normalidad de Kolmorogov-Smirnov 
```{r}
#Test de Normalizado y analisis parametrico en Total de Miembros de la Familia con Empleo
lillie.test(dbf$Total_members_employed)#Kolmorogov-Smirnov 
#ggpubr::ggqqplot(dbf$Total_members_employed)
#Cv=Ds/|X|
cv1 <-sd(dbf$Total_members_employed)/mean(dbf$Total_members_employed)
cv1
hist(dbf$Total_members_employed)
```

```{r}
#Test de Normalizado y analisis parametrico en Total de Miembros de Edad del Jefe de Casa
lillie.test(dbf$Household_Head_Age)#Kolmorogov-Smirnov
ggpubr::ggqqplot(dbf$Household_Head_Age)
#Cv=Ds/|X|
cv2 <-sd(dbf$Household_Head_Age)/mean(dbf$Household_Head_Age)
cv2
hist(dbf$Household_Head_Age)
```

```{r}
#Test de Normalizado y analisis parametrico en Inversión en Educación 
lillie.test(dbf$Education_Expenditure)#Kolmorogov-Smirnov
#Arreglo logaritmico - Revisar 
logEE <- log(dbf$Education_Expenditure)
ggpubr::ggqqplot(dbf$Education_Expenditure)
ggpubr::ggqqplot(logEE)
#Cv=Ds/|X|
cv3 <-sd(dbf$Education_Expenditure)/mean(dbf$Education_Expenditure)
cv3
hist(dbf$Education_Expenditure)
hist(logEE)
```

```{r}
#Relación entre las variables
#La libreria GGally permite observar los diagramas de dispersión, valores de correlación y la distribución de las variables en un solo gráfico
ggpairs(dbf, lower = list(continuous="smooth"),diag=list(continuous="bar"),axisLabels="none")


```
```{r}
dbfsin0 <- filter(dbf, Education_Expenditure!=0)
dbfcon0 <- filter(dbf, Education_Expenditure==0)
boxplot(dbf$Education_Expenditure+1~dbf$Main_Source_of_Income, log="y")
boxplot(dbfsin0$Education_Expenditure~dbfsin0$Main_Source_of_Income, log="y")

boxplot(dbfsin0$Education_Expenditure~dbfsin0$Household_Head_Sex, log="y")

boxplot(dbfcon0$Household_Head_Age~dbfcon0$Household_Head_Sex)

```

```{r}
hist(dbfcon0$Household_Head_Age)
hist(dbfsin0$Household_Head_Age)

hist(dbfcon0$Total_members_employed)
hist(dbfsin0$Total_members_employed)

barplot(prop.table(table(dbfcon0$Main_Source_of_Income)))
barplot(prop.table(table(dbfsin0$Main_Source_of_Income)))

barplot(prop.table(table(dbfcon0$Household_Head_Sex)))
barplot(prop.table(table(dbfsin0$Household_Head_Sex)))

plot(y=dbfsin0$Household_Head_Age, x=dbfsin0$Education_Expenditure)

ggplot(dbfsin0, aes(x=Education_Expenditure, y=Household_Head_Age)) +
  geom_point() +
  geom_smooth(method=glm , color="red", se=FALSE)
ggplot(dbfsin0, aes(x=log(Education_Expenditure), y=Household_Head_Age)) +
  geom_point() +
  geom_smooth(method=glm , color="red", se=FALSE)
```

##Modelo nulo 
```{r}
modelonulo <-lm(Education_Expenditure ~ 1, data  = dbf )

# Observamos
summary(modelonulo)

#Definir la lista de modelos
models0 <- list(modelonulo)

#Especificar los nombres del modelo
mod.names1 <- c("Modelonulo")

#Calcular el AIC de cada modelo
aictab(cand.set = models0, modnames = mod.names1)

# A simple vista se ve el modelo 1.1 es el que tiene el menor AIC por lo que peso (wt) entraría primero al modelo
```
###Modelos de primer orden 
```{r}
modelo_1.1 <-lm(Education_Expenditure ~ Household_Head_Age, data  = dbf )
modelo_1.2 <-lm(Education_Expenditure ~ Total_members_employed, data =  dbf)

# Observamos
summary(modelo_1.1)
summary(modelo_1.2)



#Definir la lista de modelos
models1 <- list(modelo_1.1, modelo_1.2)

#Especificar los nombres del modelo
mod.names1 <- c('Gastoedu y edad', 'Gastoedu y miembros ')

#Calcular el AIC de cada modelo
aictab(cand.set = models1, modnames = mod.names1)

```

###Modelos de segundo orden 
```{r}
modelo_2.1 <- lm( Education_Expenditure ~ Total_members_employed + Household_Head_Age, data=dbf )


# Observamos
summary(modelo_2.1 )

#Definir la lista de modelos
models2 <- list(modelo_2.1)

#Especificar los nombres del modelo
mod.names2 <- c('Gastomiembrosedad')

#Calcular el AIC de cada modelo
aictab(cand.set = models2, modnames = mod.names2)


```
#poisson
```{r}
ModelopNulo= glm(Education_Expenditure ~ 1, family = poisson, data =dbf)
ModelopNulo
Modelop1.1=glm(Education_Expenditure~Household_Head_Age,family = poisson, data=dbf)
Modelop1.1
Modelop1.2=glm(Education_Expenditure~Total_members_employed,family = poisson, data=dbf)
Modelop1.2
Modelop2=glm(Education_Expenditure~Total_members_employed + Household_Head_Age ,family = poisson, data=dbf)
Modelop2

CalculoPoissonAIC <- list(ModelopNulo, Modelop1.1,Modelop1.2,Modelop2)
summary(ModelopNulo)
summary(Modelop1.1)
summary(Modelop1.2)
summary(Modelop2)
models2 <- list(ModelopNulo, Modelop1.1,Modelop1.2,Modelop2)
#Especificar los nombres del modelo
NamesPoissonAIC <- c('Nulo', 'Modelo 1.1',"Modelo 1.2","Modelo 2")
#Calcular el AIC de cada modelo
aictab(cand.set = CalculoPoissonAIC, modnames = NamesPoissonAIC) # Podemos visualizar que el Modelo 2 es el que tiene el AIC menor, en conscuencia, es el mejor modelo.
```
